# Generated by Django 5.0.4 on 2024-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Name:')),
                ('description1', models.CharField(max_length=50, verbose_name='Description1:')),
                ('description2', models.TextField(verbose_name='Description2:')),
                ('price', models.FloatField(blank=True, verbose_name='Price:')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity:')),
            ],
        ),
    ]
